baseURL: "https://geobour98.github.io/"
title: geobour98
paginate: 5
theme: ["hugo-notice", "PaperMod"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-2SY6CF9Q6K

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: geobour98
  description: "geobour98's Personal Website"
  keywords: ["Blog", "Portfolio", "PaperMod"]
  #author: Me
  # author: ["Me", "You"] # multiple authors
  images: "/static/"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "logo.png"

  label:
    text: "geobour98"
    icon: "logo.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: George Bourlakis
    subtitle: "Building and breaking stuff..."
    imageUrl: "logo.png"
    imageWidth: 178
    imageHeight: 170
    imageTitle: Logo
    buttons:
      - name: About
        url: /about/
      - name: Blog
        url: /blog/
      - name: Write-ups
        url: /write-ups/
      - name: Tags
        url: /tags/

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: Email
      url: "mailto://geobour98@gmail.com"
    - name: GitHub
      url: "https://github.com/geobour98"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/George-Bourlakis/"
    - name: Twitter
      url: "https://twitter.com/geobour98"
    - name: Discord
      url: "https://discordapp.com/users/633947411672465419/"
    - name: Mastodon
      url: "https://infosec.exchange/@geobour98"

#  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
#    yandex:
#      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    #URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    includeMatches: true
    findAllMatches: true
    location: 1
    distance: 0
    threshold: 0.1
    minMatchCharLength: 1
    # search only for title
    keys: ["title"]
    # keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: Write-ups
      name: Write-ups
      url: /write-ups/
      weight: 30
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: Search
      name: Search
      url: /search/
      weight: 50

# search
outputs:
    home:
      - HTML
      - RSS
      - JSON

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
